ball_hunt:
  _target_: env.curriculum.scenario.Scenario
  name: ball_hunt
  scoring_function: 
    _target_: hydra.utils.get_method
    path: env.curriculum.scoring_functions.ball_touched
  score_threshold: 0.9
  env_config:
    obs_builder:
      _target_: env.observers.denbot_obs.DenbotObs
    action_parser:
      _target_: env.action_parser.SeerAction
    sim_setter:
      _target_: env.sim_setters.ball_hunt.BallHunt
    reward_function:
      _target_: env.denbot_reward.DenBotReward
      ball_touch: 1
      boost_collect: 0.1
      full_boost: 0
      distance_player_ball: 0.00125
      distance_ball_goal: 0
      facing_ball: 0.005
      velocity_player_to_ball: 0.005
      velocity: 0.000625
      boost_amount: 0.00125
      boost_proximity: 0.00125
    termination_condition:
      _target_: env.terminal_condition.BallTouchTermination
    truncation_condition:
      _target_: env.terminal_condition.TimeoutCondition
      timeout_seconds: 10
