wall_air_dribble:
  _target_: env.curriculum.scenario.Scenario
  name: wall_air_dribble
  scoring_function: 
    _target_: hydra.utils.get_method
    path: env.curriculum.scoring_functions.goal_scored
  score_threshold: 0.8
  env_config:
    obs_builder:
      _target_: env.observers.denbot_obs.DenbotObs
    action_parser:
      _target_: env.action_parser.SeerAction
    sim_setter:
      _target_: env.sim_setters.air_dribble.WallAirDribble
    reward_function:
      _target_: env.denbot_reward.DenBotReward
      goal_scored: 1
      ball_touch: 0.0125
      boost_collect: 0.1
      distance_player_ball: 0.000625
      offensive_angle: 0.00125
      distance_ball_goal: 0.0025
      facing_ball: 0.000625
      velocity_player_to_ball: 0.00125
      velocity_ball_goal: 0.00125
      velocity: 0.0025
      boost_amount: 0
      boost_proximity: 0
    termination_condition:
      _target_: env.terminal_condition.GoalCondition
    truncation_condition:
      _target_: env.terminal_condition.AnyCondition
      conditions:
        - _target_: env.terminal_condition.BallMinHeight
          height: 118.15  # 93.15 + 25, resting plus buffer
          delay: 2
        - _target_: env.terminal_condition.CarInFront
          buffer: 150  # About 1.5 ball radius
