defaults:
  - default

ray_init:
  local_mode: False

run_config:
  name: air_dribble
  storage_path: /home/denbuzz/src/denbot-rl/ray_results
  stop:
    training_iteration: 100000

checkpoint_config:
  num_to_keep: 5
  checkpoint_frequency: 10
  checkpoint_at_end: True

algorithm:

  environment:
    env_config: ${scenarios.ball_hunt.env_config}

  training:
    gamma: 0.993
    lambda_: 0.95
    lr: 2e-5
    entropy_coeff: 
      - [0, 0.02]
      - [1e8, 0.01]
    train_batch_size_per_learner: 16384
    num_epochs: 32
    minibatch_size: 4096
    shuffle_batch_per_epoch: True
    use_kl_loss: false

  rl_modules:
    denbot:
      _target_: hydra.utils.get_class
      path: nn.denbot.DenBot

  rl_module:
    model_config:
      pi_hiddens: [1024, 1024]
      vf_hiddens: [1024, 1024]

  callbacks:
    callbacks_class:
      _target_: env.curriculum.curriculum.CurriculumCallback
      curriculum_manager:
        _target_: env.curriculum.curriculum.CurriculumManager
        tasks:
          -
            - ${scenarios.ball_hunt}
          -
            - ${scenarios.wall_air_dribble}
            - ${scenarios.field_air_dribble}
  multi_agent:
    policies:
      - "denbot"

  env_runners:
    num_env_runners: 12
    num_envs_per_env_runner: 1
    num_cpus_per_env_runner: 1
    num_gpus_per_env_runner: 0

  learners:
    num_learners: 0
    num_gpus_per_learner: 1
